### ISSUE TITLE
Oceanbase integration causes issues with other databases

### ISSUE THREAD

**Issue by Barry-RG** [flyway/flyway-community-db-support#24]
When using Flyway with the flyway-database-oceanbase jar available in the Command Line and using a database like PostgreSQL, the query to check if the DatabaseType is correct is throwing the following error:

```SQL
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "LIKE"
  Position: 16
```

This is caused by the query in [handlesDatabaseProductNameAndVersion](https://github.com/flyway/flyway-community-db-support/blob/main/flyway-database-oceanbase/src/main/java/org/flywaydb/community/database/oceanbase/OceanBaseDatabaseType.java#L81) which fails if the Database does not support that syntax. Unfortunately, for some databases, such as PostgreSQL, if a statment fails within a transaction then the whole transaction is marked as failed and errors any following statements.

**Comment by Barry-RG** [comment]
@whhe is there any other way with Oceanbase that we could detect it. Would the String `databaseProductName`, and `databaseProductVersion` from the JDBC metadata not be usable?

**Comment by whhe** [comment]
> @whhe is there any other way with Oceanbase that we could detect it. Would the String `databaseProductName`, and `databaseProductVersion` from the JDBC metadata not be usable?

Sorry for the late reply. The `databaseProductName` returned by OceanBase is the compatibility mode, which is always 'MySQL' here. We can add a check case for it before the query.
