### ISSUE TITLE
Release versions 10.9.0, 10.9.1, 10.10.0 to be available with flyway repository

### ISSUE THREAD

**Issue by eddumelendez** [flyway/flyway-community-db-support#33]
Readme stands `Supported databases in this repository will be released as part of Flyway.` but there are a few versions not available for this artifact.

**Comment by Barry-RG** [comment]
Plugins are versioned independently of Flyway itself. The version will be increased appropriately after merging changes to this repo.
Please see https://github.com/flyway/flyway-community-db-support?tab=readme-ov-file#versioning
