### ISSUE TITLE
Mongo -  SRV Record not working

### ISSUE THREAD

**Issue by yaminidhamija** [flyway/flyway-community-db-support#51]
Getting this issue while tring to connect to Atlas Mongo using SRV Record:

[ERROR] Message    : com.mongodb.MongoConfigurationException: Failed looking up TXT record for host <hostname>
[ERROR] : class javax.naming.spi.NamingManager (in module java.naming) cannot access class com.sun.jndi.dns.DnsContextFactory (in module jdk.naming.dns) because module jdk.naming.dns does not export com.sun.jndi.dns to module java.naming

URL specified as:
flyway.url = jdbc:mongodb+srv://clustername.wff5g.mongodb.net/dbname

**Comment by Barry-RG** [comment]
I am going to close this issue as MongoDB is not a Community DB and the issue has already been raised in the appropriate repository.
